version: '3'
services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    links:
      - php
    depends_on:
      - php
      - mysql
  artisan:
    build:
      context: ./docker/artisan
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
    links:
      - mysql
    depends_on:
      - mysql
  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hBxYDGxaeY5TTa
      - MYSQL_DATABASE=personal_page
      - MYSQL_USER=sajad
      - MYSQL_PASSWORD=Tv7WXfQsmspNqA
  nodejs:
    build:
      context: docker/nodejs
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: hBxYDGxaeY5TTa
      PMA_USER: sajad
      PMA_PASSWORD: Tv7WXfQsmspNqA
volumes:
  db_data: